### ISSUE TITLE
After joining entifier, various biological models appeared in the game

### ISSUE THREAD

**Issue by ainlzj** [Lylythii/Entifier#1]
![YTI{%CEJK~B2E@DDRMTX3QG](https://user-images.githubusercontent.com/66135518/169343864-3e40a590-f124-4c10-acee-bb38fe6bc86b.png)

**Comment by ACGaming** [comment]
I believe you have just created a new species!
For real, please share your config, mod list and a recent log file as this is hard to diagnose via only a screenshot.

**Comment by ainlzj** [comment]
![屏幕截图 2022-05-22 005935](https://user-images.githubusercontent.com/66135518/169661690-2b0bf435-1b3b-4b05-8ccf-39f970b8d458.png)
[minecraft-exported-logs-2022-05-22T01-02-12.log](https://github.com/Lylythii/Entifier/files/8748016/minecraft-exported-logs-2022-05-22T01-02-12.log)

win10  i510400F 3070ti  16G

**Comment by ainlzj** [comment]
Log after deleting Entifie
[minecraft-exported-logs-2022-05-22T01-09-56.log](https://github.com/Lylythii/Entifier/files/8748028/minecraft-exported-logs-2022-05-22T01-09-56.log)
r

**Comment by ACGaming** [comment]
Were you using Thicc Entities and Entifier at the same time?

**Comment by ainlzj** [comment]
When I both exist, the game will show that there can only be one of two

**Comment by ACGaming** [comment]
I have rebuilt your mod pack according to your mod list. As it turns out, Entifier/Thicc Entities is incompatible with Epic Fight Mod. As both mods change the internals of player rendering, compatibility won‘t be easy to achieve. Choose either one for your pack.

**Comment by SticksS123** [comment]
for some reason this happens when SRPExtras is present and the effect "confused" is active
